apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "leveldb-app.fullname" . }}
spec:
  serviceName: {{ include "leveldb-app.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "leveldb-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "leveldb-app.labels" . | nindent 8 }}
      annotations:
        backup.velero.io/backup-volumes: data
    spec:
      serviceAccountName: {{ include "leveldb-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /data/leveldb
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
